title: SCRIBE Hackathon
nav_title: SCRIBE Hackathon<br> <small>Exploring data on biothreats in complex environments</small>

event_date: 17 June 2025
event_date_2: 1 July 2025
registration_opens_date: 3 April 2025

author: Jean Golding Institute, University of Bristol
mailbox_address: arcs-group@bristol.ac.uk

description:
  The SCRIBE Hackathon is a biothreat datathon to explore access, nature, and
  integration of data relating to biothreats in complex environments.
  Working with expert partners from across life sciences, we will be uncovering
  how best to unite complex data sources relating to fragile settings including
  criminal activity, conflict-affected regions, climate vulnerability, and
  complex socio-political landscapes.

footer:
  Supported and funded by the<br>
  <a href="https://bristol.ac.uk/golding/">Jean Golding Institute</a>, University of Bristol

url: "https://jgibristol.github.io"
baseurl: "/scribe-hackathon"
github_repo: JGIBristol/scribe-hackathon
code_of_conduct_url: https://bristol.ac.uk/golding/code-of-conduct/

theme: minima

# The actual visibility of the nav bar links is influenced by the event_status
# and registration_status flags below
header_pages:
  - challenges.md
  - registration.md
  - agenda.md
  - videos-slides.md
  - resources.md
  - about.md

# Event status
#   soon = event is yet to happen
#    now = event is currently happening
#   over = event has happened
#  (demo = show all pages to demonstrate the template)
event_status: soon

# Open and close the registration form
#   soon = Registration has not yet opened
#   open = Registration form is open
# closed = Registration form is now closed
#  (demo = show all pages to demonstrate the template)
registration_status: open

# Remove ".html" from default permalinks
permalink: pretty

# (See default layout below)
collections:
  challenges:
    output: true
    permalink: /:collection/:name/

# Social media links
# (See default layout below)
twitter:
  card: summary_large_image

defaults:
  - scope:
      path: ""
    values:
      image: /assets/advert.jpg
  - scope:
      path: ""
      type: "challenges"
    values:
      layout: "challenge"

# Simplify tables of contents
kramdown:
  toc_levels: "2,3"
